# Continuation to the Introduction to the tensorflow notebook ```00-tensorflow.ipynb```.


###Turn NumPy arrays into tensors






In [1]:
import tensorflow as tf
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [2]:
tf_numpy = tf.constant(numpy_A, shape=(2,3,4))
tf_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Summary-1:
* Numpy arrays can be directly be used to create tensors for various shapes.
* ```tf.constant(numpy_array, shapes(=no.of elements of the array)```

##Getting information from the tensors

In [3]:
rank_4_tensor = tf.ones(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [4]:
print(f"Datatype of the tensor elements: {rank_4_tensor.dtype}")
print(f'Number of Dimensions: {rank_4_tensor.ndim}')
print(f'Shape of tensor:{rank_4_tensor.shape}')
print(f'Elements along 0-axis: {rank_4_tensor.shape[0]}')
print(f'Elements along last-axis: {rank_4_tensor.shape[-1]}')
print(f'Total number of elements: {tf.size(rank_4_tensor)}')

Datatype of the tensor elements: <dtype: 'float32'>
Number of Dimensions: 4
Shape of tensor:(2, 3, 4, 5)
Elements along 0-axis: 2
Elements along last-axis: 5
Total number of elements: 120


##Indexing Tensors
It is similar to indexing lists

In [5]:
rank_4_tensor[0,:2] 

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [6]:
rank_3_tensor= [[[4,10],[10,1],[2,5]],[[4,10],[10,1],[2,5]]]
rank_3_tensor= tf.constant(rank_3_tensor)
rank_3_tensor, rank_3_tensor[:,2,-1]

(<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[ 4, 10],
         [10,  1],
         [ 2,  5]],
 
        [[ 4, 10],
         [10,  1],
         [ 2,  5]]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>)

In [7]:
rank_2_tensor= tf.constant([[4,10],[10,1],[2,5]])
rank_2_tensor,rank_2_tensor[:,-1]

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4, 10],
        [10,  1],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  1,  5], dtype=int32)>)

In [8]:
rank_2_tensor_new = rank_2_tensor[..., tf.newaxis]
rank_2_tensor_new

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[ 4],
        [10]],

       [[10],
        [ 1]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [9]:
tf.expand_dims(rank_2_tensor, axis=-1) #"-1 means the last axis and "0" means first aixs "

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[ 4],
        [10]],

       [[10],
        [ 1]],

       [[ 2],
        [ 5]]], dtype=int32)>

Summary-2
* Here, I understood how to analyse the datatype of the elements in the tensor, dimensions of the tensor and its shape.
* This information is crucial for the analysis of the dataset, and change the shape of the data set according to the model that is being implemented.
* Indexing the tensors is very similar to indexing the lists. Similar, concept but multiple dimensions are added.
* Just remember how the shape works, then you will understand how to slice the tensor according to your need.
* Apart from slicing, new dimensions can be added to the tensors or these tensor's dimensions can be expanded based on the axis info.
* ```tensorName[...,tf.newaxis]``` or ```tf.expand_dims(tensorName,axis= {0 or -1})```

#Manipulating Tensors (tensor operations)
**Basic Operations**

```+,-,*,/```

In [10]:
 tensor_math = tf.constant([[1,3],[1,5]])
 tensor_math

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [1, 5]], dtype=int32)>

In [11]:
tensor_math+10, tensor_math-10, tensor_math *10, tensor_math /10 #the only default with this method is that, when considered large datasets they will be inmplemented using CPU

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 13],
        [11, 15]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -7],
        [-9, -5]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 30],
        [10, 50]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.3],
        [0.1, 0.5]])>)

In [12]:
tf.math.add(tensor_math, 10), tf.math.multiply(tensor_math, 10), tf.math.subtract(tensor_math, 10), tf.math.divide(tensor_math, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 13],
        [11, 15]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 30],
        [10, 50]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -7],
        [-9, -5]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.3],
        [0.1, 0.5]])>)

In [13]:
tensor_math = tf.cast(tensor_math, dtype="float32")
tf.sqrt(tensor_math)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.7320508],
       [1.       , 2.2360678]], dtype=float32)>

Summary-3
> Tensors can be manipulated in two ways.
* Conventional way ```tensorName+num``` or any mathematical operation. But only CPU will be used in this operations and for large datasets this will not be feasible.
* Hence, using ```tf.math``` will perform these operations using GPU. So, prefer using them when implementing on a large dataset.

##Matrix Multiplication
 **Most common multiplication**

In [14]:
 tensor_matmul = tf.random.Generator.from_seed(42)
 tensor_matmul_1 = tf.cast(tensor_matmul.normal(shape=(2,3)), dtype='int32')
 tensor_matmul_2 = tf.cast(tensor_matmul.normal(shape=(3,2)), dtype='int32')
 tf.matmul(tensor_matmul_1, tensor_matmul_2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [15]:
numpy_b = np.random.randint(10,size= 9)
numpy_c = np.random.randint(10, size=6)
tens_b = tf.constant(numpy_b, shape=(3,3))
tens_c = tf.constant(numpy_c, shape=(2,3))
tens_b, tens_c


(<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[0, 1, 1],
        [5, 8, 4],
        [6, 3, 1]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[4, 3, 7],
        [9, 7, 4]])>)

In [16]:
tf_mul= tf.matmul(tens_c, tens_b)


In [17]:
tf_mul,tf.transpose(tf_mul)

(<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[57, 49, 23],
        [59, 77, 41]])>, <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[57, 59],
        [49, 77],
        [23, 41]])>)

Summary of Matrix Multiplicaton
* Always keep track of the size of matrices. Matrix of size ```3 x 3``` and ```2 x 3 ``` are not eligible to perform the operation because the size of the matrix B which is in the form ```a x b``` that is being multiplied with the matrix C which is in the form ```c x d```(matB x matC), should always follow ```a <= c```.

* Use ```tf.matmul()``` to use GPU for large scale operations.
* If the matrix dimensions are needed to be reshaped use ```tf.reshape(tensorName, shape=(a,b))```. 
* But tf.reshape does a random reshaping, but transpose just flips the access. 
* ```tf.tensordot()``` is another way of matrix multiplication. But works with both scalar and matrix quantities.
* ```tf.cast(tensorName, dtype = 'int16')``` is used to change the data type of the tensor. By default tensorflow runs on **32 bit precision**.

## Aggregation of tensors

Aggregation is nothing but reducing the large values to simpler values, that will help in analysis of the given tensors. 
**Example: Sum, min, max and etc., **


In [18]:
tf_agg_A = tf.constant(np.random.randint(1000, size=50))
tf_agg_B = tf.constant(np.random.randint(500, 1000, size = 50), shape = (2,25))
tf_agg_A, tf_agg_B

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([581, 996, 713, 205, 346, 805, 188, 604, 262, 926, 452, 342, 198,
        711, 779,   1, 569, 858, 123, 853, 804, 240,  59, 427, 183, 398,
        742, 416, 277, 976, 330, 999, 577, 651, 758, 710, 899, 573, 574,
         50, 764, 895,  23, 704, 246,  70, 416, 334, 435,  83])>,
 <tf.Tensor: shape=(2, 25), dtype=int64, numpy=
 array([[528, 868, 599, 847, 795, 910, 927, 584, 708, 881, 755, 847, 669,
         506, 574, 887, 725, 647, 621, 626, 634, 548, 580, 718, 744],
        [751, 650, 952, 516, 679, 503, 625, 593, 799, 871, 793, 784, 868,
         628, 808, 534, 733, 752, 894, 663, 857, 650, 735, 935, 541]])>)

In [19]:
tf.reduce_max(tf_agg_A), tf.reduce_max(tf_agg_B)

(<tf.Tensor: shape=(), dtype=int64, numpy=999>,
 <tf.Tensor: shape=(), dtype=int64, numpy=952>)

In [20]:
tf.reduce_min(tf_agg_A), tf.reduce_min(tf_agg_B)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=503>)

In [21]:
tf.reduce_sum(tf_agg_A), tf.reduce_sum(tf_agg_B)

(<tf.Tensor: shape=(), dtype=int64, numpy=25125>,
 <tf.Tensor: shape=(), dtype=int64, numpy=35842>)

In [22]:
tf.reduce_mean(tf_agg_A), tf.reduce_mean(tf_agg_B)

(<tf.Tensor: shape=(), dtype=int64, numpy=502>,
 <tf.Tensor: shape=(), dtype=int64, numpy=716>)

In [23]:
tf.math.reduce_variance(tf.cast(tf_agg_A, dtype = 'float32')), tf.math.reduce_variance(tf.cast(tf_agg_B, dtype = 'float32'))

(<tf.Tensor: shape=(), dtype=float32, numpy=85932.61>,
 <tf.Tensor: shape=(), dtype=float32, numpy=16751.174>)

In [24]:
tf.math.reduce_std(tf.cast(tf_agg_A, dtype = 'float32')), tf.math.reduce_std(tf.cast(tf_agg_B, dtype = 'float32'))

(<tf.Tensor: shape=(), dtype=float32, numpy=293.14264>,
 <tf.Tensor: shape=(), dtype=float32, numpy=129.42633>)

Summary-4
* ```tf.reduce_{min,max,sum, mean, prod}(tensorName)``` will directly return the respected aggregated value.
* In case of variance and standard deviation ```tf.math.reduce_variance(tensorName)``` and ```tf.math.reduce_std(tensorName)``` should be used. And these operations require only real or complex numbers **not int**.

**ArgMax and ArgMin**
Returns the index having the maximum and minimum values respectively.

In [25]:
tf_agg_B

<tf.Tensor: shape=(2, 25), dtype=int64, numpy=
array([[528, 868, 599, 847, 795, 910, 927, 584, 708, 881, 755, 847, 669,
        506, 574, 887, 725, 647, 621, 626, 634, 548, 580, 718, 744],
       [751, 650, 952, 516, 679, 503, 625, 593, 799, 871, 793, 784, 868,
        628, 808, 534, 733, 752, 894, 663, 857, 650, 735, 935, 541]])>

In [26]:
tf_agg_A[tf.argmax(tf_agg_A)]

<tf.Tensor: shape=(), dtype=int64, numpy=999>

In [27]:
tf_arg_A = tf.constant([[2,3,2], [1,5,4]])
tf_arg_A, tf.argmax(tf_arg_A)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 2],
        [1, 5, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 1])>)

In [28]:
tf_test_squeeze = tf.constant(np.random.randint(10, size=10), shape=(1,1,1,1,2,5))
tf_test_squeeze

<tf.Tensor: shape=(1, 1, 1, 1, 2, 5), dtype=int64, numpy=
array([[[[[[2, 0, 8, 4, 9],
           [5, 8, 9, 6, 1]]]]]])>

In [29]:
tf_squeezed = tf.squeeze(tf_test_squeeze)
tf_squeezed

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[2, 0, 8, 4, 9],
       [5, 8, 9, 6, 1]])>

**Summary for ArgMax & ArgMin and ```tf.squeeze(tensorName)```**
* ```tf.argmax()``` and ```tf.argmin``` returns the index of maximum and minimum elements from the tensor based on the column comparisions.
* ```tf.squeeze()``` is used to remove all the dimensions=1 from the tensor. 

## One-Hot encoding
This is used to label the data into numbers that will help the neural network to comprehend the distinguishing pattern between the data elements of classes.

In [30]:
lis_A = [1, 2, 3]
tf.one_hot(lis_A, depth = 10, on_value= 10, off_value= -1) #on and off values are just used to make customised distinction. Else set them as None.

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[-1, 10, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, 10, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, 10, -1, -1, -1, -1, -1, -1]], dtype=int32)>

# Interaction between Tensorflow and Numpy
* Both tensorflow and numpy interact very efficiently with each other. 
* But the only difference is that, tensors created using numpy ```tf.constant(np.array[])``` will have a default 64 bit precision, where as tensors created directly by ```tf.constant([])``` has a 32 bit precision.  

In [31]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [33]:
!nvidia-smi

Sat Jun 25 22:07:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P0    27W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

>**If the notebook has GPU access, tensorflow uses the GPU whenever possible.**