# Tensorflow Fundamentals Excercises

> **1. Create a vector, scalar, matrix and tensor with values of your choosing using ```tf.constant()```.**

In [1]:
import tensorflow as tf
import numpy as np
tf_vector = tf.constant([1,2,3,4])
tf_scalar = tf.constant(2)
tf_matrix = tf.constant(np.arange(0,9, dtype = np.int32), shape = (3,3))
tf_tensor = tf.constant(np.random.randint(100, size = 24, dtype = np.int32), shape = (2,3,4))
list_tensors = [tf_vector, tf_scalar, tf_matrix, tf_tensor]
tf_vector, tf_scalar, tf_matrix, tf_tensor

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 9,  7, 98, 82],
         [ 9, 13, 85, 34],
         [92, 89, 57, 31]],
 
        [[16, 38, 73, 23],
         [21, 66, 98, 18],
         [51, 31, 26, 57]]], dtype=int32)>)

> **2. Find the shape, rank and size of the tensors you created in 1.**

In [2]:
a = 1
for i in list_tensors:
  
  print(f'Tensor{a} Shape: {i.shape}')
  print(f'Tensor{a} Rank: {i.ndim}')
  print(f'Tensor{a} Size: {tf.size(i)}\n')
  a= a+1


Tensor1 Shape: (4,)
Tensor1 Rank: 1
Tensor1 Size: 4

Tensor2 Shape: ()
Tensor2 Rank: 0
Tensor2 Size: 1

Tensor3 Shape: (3, 3)
Tensor3 Rank: 2
Tensor3 Size: 9

Tensor4 Shape: (2, 3, 4)
Tensor4 Rank: 3
Tensor4 Size: 24



> **3. Create two tensors containing random values between 0 and 1 with shape ```[5, 300].```**

In [3]:
tf_random_1 = tf.constant(np.random.randint(0,2, size = 5*300, dtype = np.int32), shape = (5,300))
tf_random_2 = tf.constant(np.random.randint(0,2, size = 5*300, dtype = np.int32), shape = (5,300))

tf_random_1, tf_random_2


(<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 1, 0]], dtype=int32)>,
 <tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 0, 1, ..., 1, 0, 1],
        [1, 1, 1, ..., 1, 0, 1],
        [1, 1, 0, ..., 1, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 0, 1, ..., 0, 0, 0]], dtype=int32)>)

> **4. Multiply the two tensors you created in 3 using matrix multiplication.**

In [4]:
tf_matmul_12 = tf.matmul(tf_random_1, tf.transpose(tf_random_2))
tf_matmul_12

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[86, 74, 71, 70, 74],
       [82, 78, 76, 67, 70],
       [73, 74, 60, 57, 61],
       [77, 88, 69, 66, 64],
       [88, 90, 85, 69, 79]], dtype=int32)>

> **5. Multiply the two tensors you created in 3 using dot product.**

In [11]:
tf_dotproduct = tf.tensordot(tf_random_1, tf.transpose(tf_random_2), axes=1)
tf_dotproduct

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[86, 74, 71, 70, 74],
       [82, 78, 76, 67, 70],
       [73, 74, 60, 57, 61],
       [77, 88, 69, 66, 64],
       [88, 90, 85, 69, 79]], dtype=int32)>

> **6. Create a tensor with random values between 0 and 1 with shape ```[224, 224, 3]```.**

In [ ]:
tf_random_3 = tf.constant(np.random.randint(0,2, size = 224*224*3, dtype = np.int32), shape = (224,224,3))
tf_random_3


> **7. Find the min and max values of the tensor you created in 6 along the first axis.**

In [ ]:
tf.argmax(tf_random_3, axis=0)

In [ ]:
tf.argmin(tf_random_3)

In [31]:
tf_test = tf.constant([[[1,2,3], [4,5,6], [7,8,9]], [[11,0,31], [0,15,0], [0,81,0]]])
tf_test

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11,  0, 31],
        [ 0, 15,  0],
        [ 0, 81,  0]]], dtype=int32)>

In [28]:
tf.argmax(tf_test), tf.argmax(tf_test, axis = 1)

(<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[1, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[2, 2, 2],
        [0, 2, 0]])>)

> **8. Created a tensor with random values of shape ```[1, 224, 224, 3]``` then squeeze it to change the shape to ```[224, 224, 3]```.**

In [36]:
tf_random_4 = tf.constant(np.random.randint(0,2, size = 1*224*224*3, dtype = np.int32), shape = (1,224,224,3))
tf_random_4.shape

TensorShape([1, 224, 224, 3])

In [ ]:
tf_random_4 = tf.squeeze(tf_random_4)
tf_random_4

> **9. Create a tensor with shape ```[10]``` using your own choice of values, then find the index which has the maximum value.**

In [39]:
tf_random_5 = tf.constant(np.arange(1, 11, dtype=np.int32), shape= (10))

> **10. One-hot encode the tensor you created in 9.**

In [42]:
tf.one_hot(tf_random_5, depth=10, on_value=-1)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)>

# Tensorflow Fundamentals Extra-Curriculum

> **1. Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.**

> **2. Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
How would you calculate your grocery bill for the month and for the year using tensors?**

> **3. Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?**