# Basics of Tensorflow.

This notebook covers:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function( to speed up the python functions)
* Usings GPUs and TPUs





##Introduction to Tensors
A tensor is nothing but a description vector of an object. It can be in the form of an array or a matrix.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


####Creating tensors using tf.constant

In [ ]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [ ]:
vector = tf.constant([2,2])
print(vector)
print(vector.ndim)

tf.Tensor([2 2], shape=(2,), dtype=int32)
1


In [ ]:
matrix = tf.constant([[2,2,3],
                      [3,3,4], 
                      [1,2,3]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[2 2 3]
 [3 3 4]
 [1 2 3]], shape=(3, 3), dtype=int32)
2


In [ ]:
another_matrix = tf.constant([[[1,1,1],
                               [1,1,1]],
                              [[2,2,2],
                              [2,2,2]]], dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]]], shape=(2, 2, 3), dtype=float16)
3


Summary-1:
* Sclar: Single number
* Vecotr: Number with an array
* Matrix: 2-d array of numbers
* Tensor: n-dimensional array of numbers (It can be scalar, vector or a matrix of n-dimensions)

####Creating tensor with tf.variable

In [19]:
changeable_tensor = tf.Variable([1,2,3])
unchangable_tensor = tf.constant([4,5,6])
print(changeable_tensor)
unchangable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [20]:
changeable_tensor[0].assign(0)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([0, 2, 3], dtype=int32)>

Summary-2:
* tf.constant is used when we want certain tensors to remain constant
* tf.Variable can be changed using .assign() function

🔑 Generally, tensorflow takes care of this assignment but if ever necessary use tf.constant and change it later. 

####Creating random tensors.

In [45]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
print(random_1,"\n",random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) 
 tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [48]:
tf.random.set_seed(42)
tf.random.shuffle(random_1)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [51]:

# tf.random.set_seed(34)
tf.random.shuffle(random_2, seed= 20)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [52]:
tf.ones(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [53]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Summary-3

* Creating random tensor using  ```tf.random.Generator.from_seed()``` and the ```.normal(shape([x,y,z]))```.
* These random tensors are created because in the beginning, the hidden layer has random weights and it later changes them based on the input and output tensors.
* Shuffling the created tensors by setting the key seed value for a random shuffle using ```tf.random.set_seed(x)``` and then ```tf.random.shuffle(tensor_name)```.
* This is done so that all the input tensors are well shuffled for the hidden layer to learn from all the possible inputs.
* ```tf.ones(shape=())``` and ```tf.zeros(shape=())``` are used to create tensors of 1s and 0s of given shape.
* The major difference between tensors and numpy arrays is that tensors can also run on the GPU.

